---
- name: Fail2ban | Check installed
  apt:
    name: "{{ item }}"
  with_items:
    - fail2ban
    - ipset

- name: Fail2ban | Copy jail.d/iptables-log.conf
  copy:
    src: fail2ban/jail_iptables-log.conf
    dest: /etc/fail2ban/jail.d/iptables-log.conf
  notify: restart fail2ban

- name: Fail2ban | Copy jail.d/ssh.conf
  copy:
    src: fail2ban/jail_ssh.conf
    dest: /etc/fail2ban/jail.d/ssh.conf
  notify: restart fail2ban

- name: Fail2ban | Copy custom filter
  copy:
    src: fail2ban/iptables-log.conf
    dest: /etc/fail2ban/filter.d/iptables-log.conf
  notify: restart fail2ban

- name: Fail2ban | Check /var/log/iptables.log exists
  file:
    name: /var/log/iptables.log
    state: touch
