---
- name: Iptables | Ensure iptables installed
  apt:
    pkg: iptables-persistent
    state: present

- name: Iptables | Write iptables configuration templates
  template:
    src: etc-iptables-rules-v4.j2
    dest: /etc/iptables/rules.v4
    mode: 0640
    owner: root
    group: root
    backup: yes
  register: iptables

- name: Iptables | Configure rsyslog
  copy:
    src: rsyslog.d/iptables.conf
    dest: /etc/rsyslog.d/iptables.conf
    mode: 0644
    owner: root
    group: root
  notify: restart rsyslog

- name: Iptables | Configure logrotate
  copy:
    src: logrotate/iptables
    dest: /etc/logrotate.d/iptables
    mode: 0644
    owner: root
    group: root

- name: Iptables | Restart
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - "{{ iptables_service }}"
    - fail2ban
