---
- name: restart iptables-persistent
  service: 
    name: "{{ iptables_service }}"
    state: restarted

- name: restart fail2ban
  service: 
    name: fail2ban
    state: restarted

- name: restart rsyslog
  service: 
    name: rsyslog
    state: restarted
